music_directory "~/torrents/what-i-listen-to/"
playlist_directory "~/.mpd/playlists"
db_file "~/.mpd/database"
log_file "~/.mpd/log"
bind_to_address "127.0.0.1"
filesystem_charset "UTF-8"
port "40220"
audio_output {
    type "pipewire"  # or "alsa" depending on your setup
    name "My Audio"
}
